### ISSUE TITLE
empty mac address leads to wlan0 configuration failure

### ISSUE THREAD

**Issue by limingchina** [maemo-leste/leste-config#3]
For me, 

the statement 
`eval < "$mac_file"`
in
https://github.com/maemo-leste/leste-config/blob/master/leste-config-n900/etc/network/if-pre-up.d/00mac.leste
Doesn't work for me. it evaluates to an empty string for the variable `$macaddr`
This leads to error when configuring wlan0 during startup: `"" is invalid lladdr`

When I change the statement to the following
`val "$(cat $mac_file)"`
It's working for me.

**Comment by limingchina** [comment]
Reflashed the mmc card. The issue is not there any more. Somehow maybe related to my modified files/settings in the system.

**Comment by limingchina** [comment]
Actually the issue still exists. I still see the error message during startup. However, it doesn't seem to affect the Wifi functionality. I suspect the wlan0 interface is brought up later by some other action.

**Comment by MerlijnWajer** [comment]
@parazyd - can you take a look?

**Comment by MerlijnWajer** [comment]
Thanks for the report @limingchina !

**Comment by limingchina** [comment]
Looks like this patch fixed the reported issue. https://github.com/maemo-leste/leste-config/commit/9cb84067714902cea3bfe75cca48656a93a74fbd

**Comment by MerlijnWajer** [comment]
Thanks for checking that it is indeed fixed and for closing the issue. Please let us know if you have other feedback or questions.
